// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evjnmspquftkugrgjkmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2am5tc3BxdWZ0a3Vncmdqa21rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODQ1ODIsImV4cCI6MjA3MzA2MDU4Mn0.lu6puVoIp0schErQT6mRlpyuUSjIqg6aMDydfTo9Nj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});